### ISSUE TITLE
Return value could be confusing on piece.rb

### ISSUE THREAD

**Issue by jeremyf** [sudo-chess/chess-app#52]
In Ruby a String evaluates to true. If we attempt to move something that isn't diagonal, vertical, or horizontal, the return value will behave as if it were `true`. Is this a desired behavior?

https://github.com/sudo-chess/chess-app/blob/5c4e432f1a559216b74de68e256ba7d4af010376/app/models/piece.rb#L37

**Comment by guillaumebihet** [comment]
Thank you for this precision, yes it's ok to evalutate it as true because in that case the is_obstructed? will return true as you said, so the move will not be allowed. The method is not called for the knight so there is no risk of this non vertical/horizontal/diagonal to create an issue. 
This being said it's a good point because before to call this we check if the move is valid with the valid_move? method, so I assume it is redundant, but I'd say it's just a safety net for wrong input and it has an associated test..
